version: "3.3"
services:
  api:
    build: 
      args:
        user: flok
        uid: 1000
      context: ./
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - TZ=Africa/Lagos
    volumes:
      - ./:/var/www
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./supervisord/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./supervisord/conf.d/flok_worker.conf:/etc/supervisor/conf.d/flok_worker.conf
    command: ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    links:
      - api
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx-production/logs:/var/log/nginx
      - ./nginx-production:/etc/nginx/conf.d