# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4-cli
        environment:
          TZ: Africa/Lagos
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: flok-test
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_PASSWORD:
        volumes:
          - ./supervisord/supervisord.conf:/etc/supervisor/supervisord.conf
          - ./supervisord/conf.d/flok_worker.conf:/etc/supervisor/conf.d/flok_worker.conf
        command: ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: flok-test
      #
      - image: redis:latest

    steps:
      - checkout

      - run: sudo apt update
      - run: sudo apt-get install -y zlib1g-dev libsqlite3-dev
      - run: sudo apt-get install -y libpng-dev libjpeg62-turbo-dev
      - run: sudo apt-get install -y git curl libonig-dev libxml2-dev libzip-dev zip unzip
      - run: sudo apt-get install -y ffmpeg
      - run: sudo apt-get install -y supervisor
      - run: sudo pecl install -o -f redis &&  sudo rm -rf /tmp/pear &&  sudo docker-php-ext-enable redis
      - run: sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/*
      - run: sudo apt install libsodium-dev
      - run: sudo docker-php-ext-configure sodium
      - run: sudo docker-php-ext-install sodium
      # - run: sudo pecl install -f libsodium
      # - run: sudo docker-php-ext-enable sodium
      - run: sudo docker-php-ext-install pdo_mysql
      - run: sudo docker-php-ext-install pcntl
      - run: sudo docker-php-ext-install exif
      - run: sudo docker-php-ext-install bcmath
      - run: sudo docker-php-ext-install gd
      - run: sudo docker-php-ext-install zip

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: cp .env.example .env
      - run: php artisan key:generate
      - run: php artisan migrate:fresh
      - run: php artisan db:seed --class=TestingSeeder
      - run: ./vendor/bin/tlint
      - run: php artisan test
